#!/bin/env bash

# Arch Linux 安装脚本
# 功能：系统基本配置，软件安装
# 另外System Boot 手动安装：grub/system-boot
# system-boot 参考：https://www.cio.com/article/3098030/linux/how-to-install-arch-linux-on-dell-xps-13-2016-in-7-steps.html#slide5


# 配置区域和时间
echo 'Config charset and timezone.'
sed -i -e '/#en_US\.UTF-8/s/^.//' -e '/#zh_CN\.UTF-8/s/^.//' /etc/locale.gen
locale-gen > /dev/null
echo LANG=en_US.UTF-8 > /etc/locale.conf

date
read -p 'Is the time correct? [Y/n] ' -n1 answer
case $answer in
  y|Y) : ;;
  n|N)
    if [ -f /etc/localtime ] ; then
      mv /etc/localtime /etc/localtime.bak
    fi
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    hwclock --systohc --utc
    ;;
  *) :
esac

# 设置主机名，创建用户并赋予 root 权限
echo
echo 'Add user and config password.'
echo codcodog > /etc/hostname
echo 'password for root.'
passwd

useradd -m -g users -G wheel,storage,power -s /bin/bash cryven
echo 'passwd for cryven.'
passwd cryven

sed -i '/# %wheel ALL=(ALL) ALL/s/^..//' /etc/sudoers

# 配置镜像
sed -i '6 a # China\
Server = http://mirros.163.com/archlinux/$repo/os/$arch\
Server = http://mirrors.aliyun.com/archlinux/$repo/os/$arch\
Server = http://mirros.sohu.com/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist

# 安装软件
pacman -S iw wpa_supplicant dialog bash-completion xorg xorg-xinit\
  xf86-video-nouveau awesome terminator chromium firefox wqy-microhei fcitx\
  fcitx-im fcitx-configtool fcitx-sunpinyin shadowsocks-qt5 ranger thunar\
  ntfs-3g gvfs-mtp gvim httpie mysql-workbench

echo 'Finish system basic config, but still need to install system boot manually.'
exit 0
