#!/bin/env bash

# Arch Linux 安装脚本
# 脚本执行前提条件：系统分好盘，格式化，并挂载

# 检查网络和配置镜像
echo '配置网络和镜像...'
if ! ping -c3 cn.bing.com >/dev/null 2>&1 ; then
  echo 'Not yet connected the network.'
  exit 1
fi

sed -i '6 a # 国内源\
Server = http://mirrors.aliyun.com/archlinux/$repo/os/$arch\
Server = http://mirros.163.com/archlinux/$repo/os/$arch\
Server = http://mirros.sohu.com/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist

# 安装基础系统
echo '安装基础系统...'
if ! lsblk | grep 'mnt' > /dev/null; then
  echo '/mnt has not been mounted.'
  exit 1
fi
pacstrap -i /mnt base base-devel

# 配置 fstab, 并切换到新系统
echo '配置 fstab 并切换到新系统...'
genfstab -U -p /mnt >> /mnt/etc/fstab
arch-chroot /mnt

# 配置区域和时间
echo '配置区域和时间...'
sed -i -e '/#en_US\.UTF-8/s/^.//' -e '/#zh_CN\.UTF-8/s/^.//' /etc/locale.gen
locale-gen > /dev/null
echo LANG=en_US.UTF-8 > /etc/locale.conf

date
read -p 'Is the time correct? [Y/n] ' -n1 answer
case $answer in
  y|Y) : ;;
  n|N)
    if [ -f /etc/localtime ] ; then
      mv /etc/localtime /etc/localtime.bak
    fi
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    hwclock --systohc --utc
    ;;
  *) :
esac

# 设置主机名，创建用户，赋予权限
echo '设置主机名和创建用户...'

echo codcodog > /etc/hostname

echo 'password for root.'
passwd

useradd -m -g users -G wheel,storage,power -s /bin/bash cryven
echo 'passwd for cryven.'
passwd cryven

sed -i '/# %wheel ALL=(ALL) ALL/s/^..//' /etc/sudoers

# 安装软件
pacman -S iw wpa_supplicant dialog bash-completion git xorg xorg-xinit xf86-video-nouveau\
  awesome terminator chromium wqy-microhei fcitx fcitx-im fcitx-configtool fcitx-sunpinyin\
  shadowsocks-qt5 ranger thunar ntfs-3g gvfs-mtp gvim

# yaourt
git clone https://aur.archlinux.org/package-query.git
cd package-query
makepkg -si

cd ..
git clone https://aur.archlinux.org/yaourt.git
cd yaourt
makepkg -si
