#!/bin/sh
xrandr --output LVDS-1 --mode 1366x768 --pos 1080x0 --rotate normal --output DP-1 --off --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate left --output VGA-1 --primary --mode 1920x1080 --pos 2446x0 --rotate normal
